name: Dependency Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        if [ -f ../../package-lock.json ]; then
          npm ci
        else
          npm install
        fi
    # NPM Audit for vulnerability scanning
    - name: NPM Security Audit
      run: |
        npm audit --audit-level=high || true
    
    # Optional: OWASP Dependency-Check for comprehensive scanning
    - name: OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'My Project'
        path: '.'
        format: 'HTML, SARIF'
        out: 'reports' 
        severity: 'high'
    
    # Upload vulnerability scan results as artifacts
    - name: Upload Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: reports/
    
    # Optional: Upload results to GitHub Security
    - name: Upload to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports/dependency-check-report.sarif
